### ISSUE TITLE
Task List

### ISSUE THREAD

**Issue by iamclaytonray** [iamclaytonray/git-training#1]
- [ ] Getting Started (Env, committing, etc. Just the basics)
- [ ] Submitting PRs (code reviews, multiple PRs in a single codebase, etc)
- [ ] Let's create a convention on labels, colors, etc. Makes for a consistent issue tracker across orgs.
- [ ] Other stuff I am not thinking about right now.
